console.log("-------Deployment testing starts here------------------");
console.log(process.env.APPLICATION_PORT)
console.log(process.env.APPLICATION_ENV)
console.log(process.env.MONGODB_URL)
console.log(process.env.USER_SERVICE_URL)
console.log(process.env.INTERNAL_ACCESS_TOKEN)
console.log(process.env.KAFKA_COMMUNICATIONS_ON_OFF)
console.log(process.env.KAFKA_URL)
console.log(process.env.SUBMISSION_RATING_QUEUE_TOPIC)
console.log(process.env.COMPLETED_OBSERVATION_SUBMISSION_TOPIC)
console.log(process.env.INCOMPLETE_OBSERVATION_SUBMISSION_TOPIC)
console.log(process.env.COMPLETED_SURVEY_SUBMISSION_TOPIC)
console.log(process.env.KAFKA_GROUP_ID)
console.log(process.env.IMPROVEMENT_PROJECT_SUBMISSION_TOPIC)
console.log(process.env.ELASTICSEARCH_COMMUNICATIONS_ON_OFF)
console.log(process.env.ELASTICSEARCH_HOST_URL)
console.log(process.env.ELASTIC_SEARCH_SNIFF_ON_START)
console.log(process.env.ELASTICSEARCH_ENTITIES_INDEX)
console.log(process.env.ML_CORE_SERVICE_URL)
console.log(process.env.ML_PROJECT_SERVICE_URL)
console.log(process.env.KEYCLOAK_PUBLIC_KEY_PATH)
console.log("-------Deployment testing ends   here------------------");
