module.exports = {
    "CONFIGURATIONS_NOT_FOUND": "No configurations available for given params.",
    "ENTITY_TYPES_NOT_FOUND": "No entity type found",
    "ENTITY_INFORMATION_FETCHED": "Information fetched successfully.",
    "ENTITY_INFORMATION_UPDATE": "Information updated successfully.",
    "ENTITY_ADDED": "Entity information added successfully.",
    "ENTITY_TYPES_FETCHED": "Entity types fetched successfully.",
    "ENTITY_TYPE_INDEX": "Entity type index created successfully.",
    "CONFIGURATIONS_FETCHED": "Configurations fetched successfully.",
    "USER_EXTENSION_FETCHED": "User profile fetched successfully.",
    "USER_ID_REQUIRED_CHECK": "User ID is required.",
    "ENTITY_ID_REQUIRED_CHECK": "Entity type is required.",
    "ASSESSMENT_FETCHED": "Assessment fetched successfully",
    "UNAUTHORIZED": 'Unauthorized.',
    "SOMETHING_WENT_WRONG": "Something went wrong!",
    "ASSESSOR_CREATED": "Assessor record created successfully.",
    "ASSESSOR_LIST": "List of assessors fetched successfully",
    "ASSESSOR_NOT_FOUND": "No assessor found.",
    "PENDING_ASSESSMENT": "Pending Assessments",
    "COMPLETED_ASSESSMENT": "Completed Assessments",
    "FEEDBACK_FORM_FETCHED": "Feedback from fetched successfully.",
    "FILES_NAME_NOT_GIVEN": "File names not given.",
    "URL_GENERATED": "URLs generated successfully.",
    "FRAMEWORK_NOT_FOUND": "No framework found",
    "REQUIRED_FRAMEWORK_EXTERNALID": "External Id for framework is required",
    "REQUIRED_FRAMEWORK_NAME": "Name for framework is required",
    "REQUIRED_FRAMEWORK_DESCRIPTION": "Description for framework is required",
    "REQUIRED_ENTITY_TYPE_FOR_FRAMEWORK": "Entity Type for framework is required",
    "FRAMEWORK_EXISTS": "Framework already exists",
    "FRAMEWORK_INSERTED": "Framework inserted successfully.",
    "FRAMEWORK_UPDATED": "Framework updated successfully.",
    "FRAMEWORK_DELETED": "Framework deleted successfully.",
    "FRAMEWORK_COULD_NOT_BE_DELETED": "Framework could not be deleted",
    "FRAMEWORK_EXTERNAL_ID_REQUIRED_CHECK": "Framework ExternalId is required",
    "PROGRAM_NOT_FOUND": 'No program found.',
    "ROGRAM_EXISTS": "Program already exists",
    "PROGRAM_IMPORTED": "Program imported successfully.",
    "PROGRAM_LIST": "Program information list fetched successfully.",
    "PROGRAM_ID_REQUIRED": "Program id is required",
    "SOLUTION_UPDATED": "Solution updated successfully",
    "SOLUTION_NOT_FOUND": "No solution found.",
    "SOLUTION_EXISTS": "Solution already exists",
    "SOLUTION_IMPORTED": "Solution imported successfully.",
    "SOLUTION_FETCHED": "Solutions fetched successfully",
    "SOLUTION_ID_NOT_FOUND": "Solution Id is not found",
    "SOLUTION_ID_REQUIRED": "Solution id is required",
    "SOLUTION_DELETED": "Solution deleted successfully.",
    "SOLUTION_CANT_DELETE": "Solution not found or Solution is private.",
    "SOLUTION_CANT_REMOVE": "Solution cannot be removed  ",
    "SOLUTION_MOVED_TO_TRASH": "Your solution has been moved to Trash.",
    "SOLUTION_REMOVED_FROM_HOME_SCREEN": "Your solution has been removed.",
    "SOLUTION_RESTORED_FROM_TRASH": "Solution restored successfully.",
    "SOLUTION_TRASH_LIST_FETCHED": "Trash Solution fetched successfully.",
    "OBSERVATION_LINK_FETCHED": "Observation Link fetched successfully",
    "OBSERVATION_LINK_VERIFIED": "Observation Link verified successfully",
    "APP_NOT_FOUND": "App not found",
    "CRITERIA_FILE_NOT_FOUND": "Csv file for criterias should be selected",
    "CRITERIA_INSERTED": "Criterias inserted successfully.",
    "CRITERIA_RATING": "Crtieria rating completed successfully",
    "CRITERIA_NOT_FOUND": "Criteria is not found",
    "INVALID_CRITERIA_ID": "Invalid criteria external ID.",
    "CRITERIA_QUESTION_NOT_FOUND": "No criteria question found.",
    "CRITERIA_UPDATED": "Criteria updated successfully",
    "QUESTION_INSERTED": "Questions inserted successfully.",
    "QUESTION_NOT_FOUND": "No question found",
    "QUESTION_ID_REQUIRED_CHECK": "QuestionId is required",
    "QUESTION_COULD_NOT_BE_DELETED": "Question could not be deleted",
    "QUESTION_DELETED": "Question deleted successfully.",
    "INSIGHTS_NOT_FOUND": "No insights found",
    "INSIGHTS_FETCHED": "Insights report fetched successfully.",
    "HIGH_LEVEL_INSIGHTS": "High Level Insights report fetched successfully.",
    "CREATED_BY_NOT_FOUND": "Created by is not found",
    "OBSERVATION_META_FETCHED": "Observation meta fetched successfully.",
    "OBSERVATION_CREATED": "Observation created successfully.",
    "OBSERVATION_LIST": "Observation list fetched successfully",
    "OBSERVATION_NOT_PUBLISHED": "Observation not published.",
    "OBSERVATION_NOT_FOUND": "No observation found.",
    "OBSERVATION_MARKED_COMPLETE": "Observation marked as completed.",
    "OBSERVATION_ALREADY_COMPLETED": "Observation already completed",
    "OBSERVATION_UPDATED": "Observation successfully updated.",
    "OBSERVATION_DELETED": "Observation deleted successfully.",
    "OBSERVATION_FETCHED": "Observation fetched successfully.",
    "OBSERVATION_RATING": "Observation rating completed successfully.",
    "OBSERVATION_AUTO_RATING_SUCCESS": "Observation Auto Rating Successful - ",
    "OBSERVATION_AUTO_RATING_FAILED": "Observation Auto Rating FAILED - ",
    "OBSERVATION_SUBMISSION_CREATED": "Observation submission created successfully",
    "OBSERVATION_SUBMISSION_CHECK": "Observation submission check completed successfully",
    "OBSERVATION_SUBMISSION_DELETED": "Observation submission deleted successfully",
    "OBSERVATION_SUBMISSION_UPDATED": "Observation submission updated successfully",
    "OBSERVATION_SUBMISSION_DiSABLED": "Observation submission disabled successfully",
    "OBSERVATION_LINK_GENERATED": "Observation Link generated successfully",
    "OBSERVATION_LINK_VERIFIED": "Observation solution link verified successfully.",
    "SUBMISSION_NOT_FOUND": "No submission found.",
    "SUBMISSION_FOUND": "submission found.",
    "PARENT_INFORMATION_NOT_FOUND": "No parent information found.",
    "PARENT_INTERVIEW_FETCHED": "Parent interview response fetched successfully.",
    "ENTITIES_NOT_UPDATE": "Not all entities are updated.",
    "ENTITIES_UPDATED": "Entities updated successfully.",
    "ENTITY_REMOVED": "Entity Removed successfully.",
    "ENTITY_FETCHED": "Entities fetched successfull",
    "ENTITY_NOT_FOUND": "No entitiy found",
    "ENTITY_PROFILE_FORM_NOT_FOUND": "No entity profile form found.",
    "ENTITY_ID_NOT_FOUND": "Entity Id is not found",
    "ENTITY_LIST": "List of entities fetched successfully",
    "ZONE_LIST": "List of zones fetched successfully",
    "ASSESSMENT_FETCHED": "Assessment fetched successfully",
    "INVALID_PARAMETER": "Invalid parameters.",
    "INVALID_TYPE": "Type is invalid",
    "OBSERVATION_SOLUTION": "Observation Solution generated.",
    "ERROR_CREATING_OBSERVATION": "Some error while creating observation solution.",
    "USER_NOT_FOUND": "User is not present",
    "PENDING_OBSERVATION": "Pending Observations",
    "COMPLETED_OBSERVATION": "COmpleted Observations",
    "REPORTS_FILTER": "Reports filter fetched successfully.",
    "MANAGER_PROFILE": "Manager profile fetched successfully.",
    "NO_DATA_FOUND": "No data found for given params.",
    "PARENT_NOT_FOUND": "No parent found",
    "SOLUTION_GENERATED": "Solution generated",
    "BODY_NOT_EMPTY": "Body should not be empty.",
    "DUPLICATE_SOLUTION": "Duplicate Solution generated.",
    "ERROR_CREATING_DUPLICATE": "Some error while creating duplicate solution.",
    "STATIC_LINKS_FETCHED": "Static Links fetched successfully.",
    "FILE_DATA_MISSING": "File or data is missing.",
    "PARENT_INTERVIEW_COMPLETED": "Parent Interview completed successfully.",
    "PARENT_INTERVIEW_SUBMITTED": "Parent interview submitted successfully.",
    "ALREADY_COMPLETED": "Already completed.",
    "PARENT_INTERVIEW_FAILED": "Failed to complete parent interview.",
    "GENERAL_QUESTION_SUBMITTED": "General question submitted successfully.",
    "GENERAL_QUESTION_FAILED": "Failed to submit general questions",
    "DUMMY_RATE": "Dummy Crtieria rating completed successfully",
    "SUBMISSION_CHECK": "Submission check completed successfully",
    "FEEDBACK_ERROR": "Atleast one evidence method has to be completed before giving feedback.",
    "FEEDBACK_SUBMITTED": "Feedback submitted successfully.",
    "SUBMISSION_STATUS_FETCHED": "Submission status fetched successfully",
    "ECM_REQUIRED": "Ecm is required",
    "ANSWER_MERGED": "Answers merged successfully",
    "INSUBMITTED_FALSE": "isSubmitted False",
    "VALID_INVALID_RESPONSE": "Invalid new or old response!",
    "DONE": "Done",
    "NOT_Done": "Not Done",
    "ECM_NOT_EXIST": "Ecm doesnot exists",
    "ECM_RESET": "ECM Reset successfully",
    "USER_EXTENSION_ENTITIES_FETCHED": "User Extension entities fetched successfully",
    "USER_ROLES_FETCHED": "User roles fetched successfully.",
    "CRITERIA_RUBRIC_UPDATE": "Criteria rubric updated successfully.",
    "ENTITY_INFORMATION_NOT_INSERTED": "Some entity information was not inserted!",
    "INVALID_ENTITY_TYPE": "Invalid entity type.",
    "SOMETHING_WRONG_INSERTED_UPDATED": "Something went wrong, not all records were inserted/updated.",
    "INVALID_MAPPING_DATA": "Invalid mapping data",
    "MISSING_ENTITYID_ENTITYTYPE_ENTITYTYPEID": "EntityTypeId or entityType or entityId is not found",
    "CREATE_INDEX": "Index successfully created.",
    "INDEX_NOT_CREATED": "Something went wrong! Couldn't create the index.",
    "WRONG_ACTION": "wrong action",
    "INVALID_USER_ID": "Invalid user id.",
    "NOTIFICATIONS_PUSHED_TO_KAFKA": "All notifications pushed to Kafka.",
    "NOTIFICATION_PUSHED_TO_KAFKA": "Notifications successfully pushed to Kafka.",
    "MISSING_ASSESSOR_LEAD_ASSESSOR": "No LEAD_ASSESSOR or ASSESSOR Found",
    "MISSING_CLOUD_STORAGE_PROVIDER": "Cloud storage provider not given.",
    "INVALID_CLOUD_STORAGE_PROVIDER": "Invalid Cloud storage provider.",
    "FAILED_PRE_SIGNED_URL": "Failed to generate pre signed URLs.",
    "FAILED_SIGNED_URL": "Failed to generated Signed URL.",
    "FOUND_SUBMISSION": "Submission found",
    "SUBMISSION_COMPLETED": "Submission completed successfully",
    "INVALID_OBSERVATION_ENTITY_ID": "Invalid observation or entity id.",
    "SUBMISSION_NUMBER_FETCHED": "Submission Number fetched successfully.",
    "NO_COMPLETED_OBSERVATIONS": "Completed observations not found",
    "NO_PENDING_OBSERVATION": "Pending observations not found",
    "SUBMISSION_STATUS_NOT_COMPLETE": "Submission status is not completed",
    "OBSERVATION_SUBMISSION_ID_NOT_FOUND": "No observation submission id found",
    "OBSERVATION_SUBMISSSION_NOT_FOUND": "No observation submission found",
    "MISSING_NAME_EXTERNALID": "Name or externalId is missing ",
    "THEME_SUBTHEME_FAILED": "Failed to find a matching theme or sub-theme with the same external id and name.",
    "CRITERIA_WEIGHTAGE_NOT_UPDATED": "Something went wrong! Not all criteira weightage were updated.",
    "ALL_ECM_NOT_COMPLETED": "Sorry! All evidence methods have to be completed to enable ratings.",
    "ASSESSMENT_BLOCK_FOR_RATING": "Sorry! This could be because the assessment has been blocked. Resolve conflicts to proceed further.",
    "DUPLICATE_ECM_SUBMISSION": "Duplicate evidence method submission detected.",
    "ALL_ECM_NOT_SUBMITTED": "All ECM are not submitted",
    "SUBMISSION_ID_NOT_FOUND": "No submission id found",
    "SUBMISSION_RATING_COMPLETED": "Submission rating completed successfully.",
    "SUBMISSION_PROCESSED_FOR_MANUAL_RATING": "Submission processed for manual rating successfully.",
    "SUBMISSION_AUTO_RATING_SUCCESS": "Submission Auto Rating Successful - ",
    "SUBMISSION_AUTO_RATING_FAILED": "Submission Auto Rating FAILED - ",
    "INVALID_ROLE_CODE": "Invalid role code.",
    "INVALID_ENTITY_OPERATION": "Invalid entity operation.",
    "INVALID_ENTITY_ID": "Invalid entity id.",
    "KEYCLOAK_USER_ID": "Keycloak user ID is mandatory.",
    "USER_ENTITY_ID": "User entity id.",
    "USER_EXTENSION_NOT_FOUND": "User Extension not found .",
    "MISSING_EMAIL_RECIPIENTS": "Email Recipients Missing.",
    "NOT_FOUND": "Not found!",
    "STATUS_COMPLETED": "completed",
    "REQUIRED_FROM_DATE": "From date is required",
    "REQUIRED_USER_AUTH_TOKEN": "User auth token is required",
    "REQUIRED_AUTH_TOKEN_OR_USER_ID": "Auth token or user id is missing.",
    "USER_ORGANISATION_DETAILS_NOT_FOUND": "Cannot create an observation for user whose organisation details are not available",
    "QUESTIONS_FILE_REQUIRED": "Required questions key in form-data",
    "ENTITY_GROUPS_NOT_FOUND": "Entity groups could not be found",
    "UNNATI_SERVICE_DOWN": "Unnati service is down",
    "PROGRAM_NOT_MAPPED_TO_USER": "No program mapped to user",
    "SOLUTION_NOT_MAPPED_TO_USER": "No solution mapped to user",
    "ENTITIES_NOT_MAPPED_TO_USER": "No entities mapped to user",
    "USER_ENTITIES_FETCHED_SUCCESSFULLY": "Successfully fetched user entities",
    "USER_PROGRAMS_LIST_FETCHED": "Sucessfully fectched user programs",
    "OBSERVATION_SUBMISSIONS_LIST_FETCHED": "Successfully fetched observation submissions",
    "TEMPLATE_SOLUTIONS_FETCHED": "Template solutions fetched successfully",
    "SOLUTION_META_FORM_FETCHED": "Solution meta form fetched successfully",
    "CREATED_SOLUTION": "Successfully created solution",
    "TEMPLATE_SOLUTION_DETAILS_FETCHED": "Template solution details fetched successfully",
    "OBSERVATION_SOLUTION_NOT_CREATED": "Could not create observation solution",
    "OBSERVATION_NOT_CREATED": "Could not create observation",
    "OBSERVATION_SOLUTION_DETAILS": "Successfully fetched observation solution details",
    "INSTITUTIONAL_SOLUTIONS_FETCHED": "Successfully fetched institutional solutions",
    "INSTITUTIONAL_SOLUTIONS_DETAILS": "Successfully fetched institutional solution detail",
    "FORM_NOT_FOUND": "No form found",
    "INSTITUTIONAL_SOLUTIONS_LIST": "Successfully fetched institutional solutions list",
    "INDIVIDUAL_SOLUTIONS_LIST": "Successfully fetched individual solutions list",
    "INDIVIDUAL_SOLUTIONS_DETAILS": "Successfully fetched individual solution details",
    "OBSERVATION_SOLUTIONS_LIST": "Successfully fetched observations solutions list",
    "PRIVATE_PROGRAMS_LIST": "List of private programs",
    "USER_PROGRAMS_FETCHED": "Successfully fetched user programs",
    "SUBMISSION_DELETED": "Submission deleted successfully",
    "SUBMISSION_UPDATED": "Submission updated successfully",
    "SUBMISSION_CREATED": "Submission created successfully",
    "LIBRARY_CATEGORY_FETCHED": "Library categories fetched successfully",
    "LIBRARY_CATEGORIES_NOT_FOUND": "Could not found library categories",
    "URL_COULD_NOT_BE_FOUND": "Could not found url from gcp",
    "KENDRA_SERVICE_DOWN": "Kendra service is down",
    "SUBMISSION_LIST_FETCHED": "Submission list fetched successfully",
    "CRITERIA_QUESTIONS_FETCHED_SUCCESSFULLY": "Criteria questions fetched successfully",
    "MANUAL_RATING_SUBMITTED_SUCCESSFULLY": "Manual rating submitted successfully",
    "RATING_COULD_NOT_BE_SUBMITTED": "Rating could not be submitted",
    "FETCH_CRITERIA_QUESTIONS_FAILURE": "Rating is already submitted or rating submission is not allowed.",
    "SUBMISSION_ID_IS_REQUIRED": "SubmissionId is a required field",
    "CRITERIA_OBJECT_MISSING": "Criteria Object should contain atleast one criteriaId",
    "CRITERIA_LENGTH_MISMATCH": "Criteria length is mismatching",
    "CRITERIA_QUESTIONS_COULD_NOT_BE_FOUND": "Criteria questions could not be found",
    "SUBMISSION_CRITERIA_NOT_FOUND": "Criteria not found for the submissionId",
    "POLL_CREATION_FORM_FETCHED": "Poll creation form fetched successfully",
    "POLL_CREATED": "Poll created successfully",
    "POLLS_LIST_FETCHED": "Polls list fetched successfully",
    "POLL_DELETED": "Poll deleted successfully",
    "POLL_SUBMITTED": "Poll submitted successfully",
    "POLL_NAMES_FETCHED": "Poll names fetched successfully",
    "POLL_REPORT_CREATED": "Poll report created successfully",
    "POLL_QUESTIONS_FETCHED": "Poll questions fetched successfully",
    "EMOJI_CREATED": "Emoji created successfully",
    "GESTURE_CREATED": "Gesture created successfully",
    "EMOJI_FETCHED": "Emoji fetched successfully",
    "GESTURE_FETCHED": "Gesture fetched successfully",
    "POLL_ID_REQUIRED_CHECK": "PollId is required",
    "POLL_NOT_FOUND": "Poll not found",
    "POLL_COULD_NOT_BE_SUBMITTED": "Poll could not be submitted",
    "POLL_DATA_REQUIRED": "PollData is required",
    "RESPONSE_OBJECT_REQUIRED_CHECK": "ResponseObject is required",
    "MULTIPLE_SUBMISSIONS_NOT_ALLOWED": "Multiple submissions not allowed",
    "POLL_SUBMISSION_DOCUMENTS_NOT_FOUND": "Poll submission documents not found",
    "NAME_REQUIRED_CHECK": "Name is required",
    "UNICODE_REQUIRED_CHECK": "Unicode is required",
    "EMOJI_NOT_FOUND": "Emoji not found",
    "GESTURE_NOT_FOUND": "Gesture not found",
    "LINK_IS_EXPIRED": "Link is expired",
    "LINK_REQUIRED_CHECK": "Link is required",
    "POLL_UPDATED": "Poll document updated successfully",
    "UPDATE_OBJECT_REQUIRED": "UpdateObject required",
    "POLL_SUBMISSIONS_NOT_FOUND": "Poll submissions not found",
    "POLL_IS_INACTIVE": "Poll is inactive",
    "POLL_VALIDATED": "Poll validated successfully",
    "POLL_SUBMISSION_VALIDATED": "Poll submission can be done",
    "POLL_LINK_FETCHED": "Poll link fetched successfully",
    "POLL_COULD_NOT_BE_DELETED": "Poll could not be deleted",
    "POLL_UPDATE_QUERY_REQUIRED": "Update query is required",
    "POLL_COULD_NOT_BE_UPDATED": "Poll updation failed",
    "APP_NOT_FOUND": "App not found",
    "SOLUTION_NAME_REQUIRED": "Solution name is required",
    "SOLUTION_EXTERNAL_ID_REQUIRED": "Solution external id is required",
    "SOLUTION_DESCRIPTION_REQUIRED": "Solution description is required",
    "SURVEY_SOLUTION_CREATED": "Survey solution template created successfully",
    "ERROR_CREATING_SURVEY_SOLUTION": "Error while creating survey solution.",
    "SURVEY_SOLUTIONS_LIST_FETCHED": "Survey solutions list fetched successfully",
    "APP_NAME_FIELD_REQUIRED": "App name field required",
    "SURVEY_SOLUTION_DETAILS_FETCHED": "Survey solution details fetched successfully",
    "SURVEY_NOT_FOUND": "Survey not found",
    "SURVEY_ALREADY_EXISTS": "Survey already exists for the user",
    "SURVEY_DETAILS_FETCHED_SUCCESSFULLY": "Survey details fetched successfully",
    "COULD_NOT_FETCH_SURVEY_DETAILES": "Survey details fetching failed",
    "REQUEST_DETAILS_REQUIRED": "Request details required",
    "MAKE_SUBMISSION_FAILED": "Could not make submission",
    "SURVEY_SUBMISSION_ID_REQUIRED": "Survey submission id required",
    "SURVEY_SUBMISSION_CREATED": "Survey submitted successfully",
    "SURVEY_CREATION_FAILED": "Survey creation failed",
    "SURVEY_LIST_FETCHED": "survey list fetched successfully",
    "SOLUTION_EXTERNAL_ID_REQUIRED": "Solution external id is required",
    "SURVEY_SUBMISSION_CHECK": "Survey submission check completed successfully",
    "EVIDENCE_ID_REQUIRED": "Evidence id is required",
    "ORGANISATION_DETAILS_NOT_FOUND_FOR_USER": "Cannot create an survey for user whose organisation details are not available",
    "SUBMISSION_STATUS_FETCHED": "Submission status fetched successfully",
    "USER_ORGANISATION_DETAILS_FETCHED": "User organisation details fetched successfully",
    "SOLUTION_ID_REQUIRED": "Solution id is required",
    "SURVEY_SOLUTION_IMPORTED": "Survey solution imported successfully",
    "ERROR_IMPORTING_SURVEY_SOLUTION": "Error while importing survey solution",
    "MAPPED_SOLUTION_TO_PROGRAM": "Mapped survey solution to program successfully",
    "UPDATE_QUERY_REQUIRED": "Update query is required",
    "UPDATE_OBJECT_REQUIRED": "Update object is required",
    "FAILED_TO_UPDATE": "Failed to update the document",
    "UPDATED_DOCUMENT_SUCCESSFULLY": "Document updated successfully",
    "USER_EXTENSION_COULD_NOT_BE_UPDATED": "User Extension updation failed",
    "USER_EXTENSION_UPDATED": "User Extension updated",
    "APP_DETAILS_NOT_FOUND": "App not found",
    "OBSERVATION_SUBMISSION_ID_REQUIRED": "Observation submission id required",
    "INVALID_LINK": "Invalid link",
    "CRITERIA_ID_NOT_FOUND": "Criteria ids not found",
    "DUPLICATED_CRITERIA_SUCCESSFULLY": "Duplicated criterias successfully",
    "QUESTION_ID_REQUIRED": "QuestionIds are required",
    "DUPLICATED_QUESTIONS_SUCCESSFULLY": "Duplicated questions successfully",
    "THEMES_REQUIRED": "Themes required",
    "CRITERIA_ID_REQUIRED": "Criteria ids required",
    "QUESTION_ID_NOT_FOUND": "Question ids not found",
    "OBSERVATION_SUBMISSION_STATUS_FETCHED": "Observation submission status fetched successfuly",
    "USERS_AND_ENTITIES_NOT_FOUND": "Could not find users for the given entity and role",
    "ENTITY_ASSESSORS_CREATED": "Successfully created entity assessors",
    "PROGRAM_UPDATED_SUCCESSFULLY": "Successfully updated program",
    "SURVEYS_FETCHED": "Surveys fetched successfully",
    "TARGETED_SURVEY_FETCHED": "Targeted surveys fetched successfully",
    "TARGETED_SOLUTIONS_FETCHED": "Successfully targeted solutions fetched",
    "ENTITIES_NOT_FOUND": "No entities found",
    "OBSERVATION_ENTITIES_FETCHED": "Observation entities fetched successfully",
    "ENTITY_TYPE_MIS_MATCHED": "Provided solution entity type mis matched",
    "TARGETED_OBSERVATION_FETCHED": "Targeted observations fetched successfully",
    "ENTITIES_NOT_FOUND": "No entities found",
    "OBSERVATION_ENTITIES_FETCHED": "Observation entities fetched successfully",
    "ENTITY_TYPE_REQUIRED_IN_SCOPE": "Required entity type in scope",
    "ENTITIES_REQUIRED_IN_SCOPE": "Entities required in scope",
    "ROLE_REQUIRED_IN_SCOPE": "Required role in scope",
    "PROGRAM_UPDATED_SUCCESSFULLY": "Program updated successfully",
    "TARGETED_PROGRAMS_FETCHED": "Targeted programs fetched successfully",
    "SCOPE_ENTITY_INVALID": "Scope entity is invalid",
    "SOLUTION_SCOPE_NOT_ADDED": "Could not add solution scope",
    "SOLUTION_CREATED": "Solution created successfully",
    "ENTITY_TYPE_MIS_MATCHED": "Provided solution entity type mis matched",
    "USER_SURVEYS_FETCHED": "User's surveys fetched successfully",
    "INVALID_SCOPE_SOLUTION": "Solution does not have scope",
    "PROGRAM_DESCRIPTION": "View and participate in educational programs active in your location and designed for your role",
    "NO_ENTITY_FOUND_IN_LOCATION": "Entity not found in location",
    "ENTITIES_REGISTRY_DETAILS_UPDATED": "Entities Registry Details Updated.",
    "ENTITIES_FETCHED": "Entities fetched successfully.",
    "REGISTRY_FILE_NOT_FOUND": "Csv file for registry should be selected",
    "REGISRY_NEED_TO_BE_ADD": "Entity found in DB but not found in input sheet",
    "ENTITY_NOT_FOUND_IN_PARENT_ENTITY_GROUP":"Entity not found in parent entity group",
    "SOLUTION_DETAILS_NOT_FOUND" : "Could not found solution details",
    "INVALID_PARENT_ENTITY" : "Parent entity is invalid",
    "ENTITY_NOT_UPDATED" : "Could not updated entity",
    "CREATOR_CAN_NOT_SUBMIT_SURVEY" : "You are survey creator, you can not submit the survey",
    "APP_INFORMATION_ADDED" : "App information added successfully in submission",
    "CRITERIA_COULD_NOT_BE_DELETED": "Could not found criteria",
    "CRITERIA_REMOVED": "Criteria removed successfully",
    "THEMES_NOT_FOUND":"Themes Not Found",
    "USER_ASSIGNED_OBSERVATION_FETCHED" : "List of user assigned observations",
    "USER_ASSIGNED_SURVEY_FETCHED" : "List of user assigned surveys",
    "SUBMISSION_NOT_ALLOWED" : "Submission not allowed",
    "SUBMISSION_ALLOWED" : "Submission is allowed",
    "USER_ORGANISATION_NOT_FOUND" : "User organisation details not found",
    "SURVEY_LINK_GENERATED" : "Survey solution link generated successfully"
}
