module.exports = {
  name: "schools",
  schema: {
    // form: Object,
    "externalId": "String",
    "addressLine1": "String",
    "addressLine2": "String",
    "city": "String",
    "country": "String",
    "createdBy": "String",
    "createdDate": "String",
    "gpsLocation": "String",
    "isDeleted": false,
    "name": "String",
    "phone": "String",
    "principalName": "String",
    "state": "String",
    "status": "String",
    "updatedBy": "String",
    "updatedDate": "String",
    "pincode": "String",
    "districtId": "String",
    "districtName": "String",
    "zoneId": "String",
    "administration": "String",
    "gender": "String",
    "shift": "String",
    "schoolTypes": Array,
    "totalStudents": Number,
    "totalGirls": Number,
    "totalBoys": Number,
    "lowestGrade": "String",
    "highestGrade": "String",
    "isParentInterviewCompleted": false,
    "totalSection": Number, 
    "totalTeachersPresentInTheSchool": Number, 
    "totalEnglishTeachers": Number, 
    "totalHindiTeachers": Number, 
    "totalMathsTeachers": Number, 
    "totalScienceTeachers": Number, 
    "totalSocialTeachers": Number, 
    "totalSocialScienceTeachers": Number, 
    "totalComputerTeachers": Number, 
    "totalStudentsInGrade9": Number,
    "totalStudentsInGrade10": Number,
    "totalStudentsInGrade11": Number,
    "totalStudentsInGrade12": Number,
    "mediumOfInstruction": "String",
    "totalSanctionedTeachingPosts": Number ,
    "totalFilledTeachingPosts": Number ,
    "totalPermanentTeachers": Number ,
    "totalGuestTeachers": Number ,
    "totalPrimaryTeachersHavingDiploma": Number ,
    "totalTeachersTeaching6to10": Number ,
    "totalCTETQualifiedTeachers": Number ,
    "totalStudentsAdmittedIn2018-19InLowestClass": Number ,
    "totalEWS/DGStudentsStudyingIn2018-19InLowestClass": Number ,
    "totalStudentsAdmittedLastYearInLowestClass": Number ,
    "totalEWS/DGStudentsAdmittedLastYearInLowestClass": Number ,
    "totalEWS/DGStudentsCurrentlyStudyingInSecondLowestClass": Number ,
    "totalPhysicsTeachers": Number , 
    "totalChemistryTeachers": Number , 
    "totalBiologyTeachers": Number , 
    "totalEconomicsTeachers": Number , 
    "totalPoliticalScienceTeachers": Number , 
    "totalAccountsTeachers": Number , 
    "totalBusinessStudiesTeachers": Number , 
    "totalHistoryTeachers": Number , 
    "totalGeographyTeachers": Number , 
    "streamOffered": "String" ,
  }
};